@startuml

class Species {
  # speciesID
  # speciesName
  + __construct(speciesID, speciesName)
  + getID()
  + getName()
}

class Pricing {
  # petID
  # toyID
  # adoptionPrice
  # toysPrice
  + __construct(adoptionPrice, toysPrice)
  + getID()
  + getAdoptionPrice()
  + setAdoptionPrice()
  + getToysPrice()
  + setToysPrice()
}

class Breeds {
  # breedID
  # breedType
  # speciesID
  # description
  + __construct(breedID, breed, speciesID, description)
  + getID()
  + getBreedType()
  + getSpeciesID()
  + getDescription()
}

class Pets {
  # petID
  # petName
  # breedType
  # speciesID
  # age
  # gender
  # description
  # isVaccinated
  # isTrained
  + pricing
  + __construct(petID, petName, breed, speciesID, age, gender, description, pricing, isVaccinated, isTrained)
  + getID()
  + getName()
  + setName()
  + getBreedType()
  + getDescription()
  + getPricing()
  + eat()
  + sleep()
  + play()
  + run()
  + getIsVaccinated()
  + setIsVaccinated()
  + getIsTrained()
  + setIsTrained()
}

class Dog extends Pets {
  # size
  + __construct(petID, petName, breedType, speciesID, age, gender, description, pricing, isVaccinated, isTrained, size)
  + getSize()
  + bark()
  + fetch()
  + swim()
}

class Cat extends Pets {
  # furType
  + __construct(petID, petName, breedType, speciesID, age, gender, description, pricing, isVaccinated, isTrained, furType)
  + getFurType()
  + meow()
  + playWithToy()
}

class Duck extends Pets {
  # featherColor
  + __construct(petID, petName, breedType, speciesID, age, gender, description, pricing, isVaccinated, isTrained, featherColor)
  + getFeatherColor()
  + quack()
  + swim()
  + fly()
}

class Toys {
  # toyID
  # toyName
  # description
  # applicableSpecies
  + pricing
  + __construct(toyID, toyName, description, applicableSpecies, pricing)
  + getID()
  + getName()
  + getApplicableSpecies()
  + getPricing()
}

Species <|-- Toys
Species --|> Breeds
Breeds --|> Pets

Toys --|> Pricing

@enduml





' extend toys to species to breeds to pets
' add more properties for each classes (desc, color, age, gender)
' maybe change breedName to breed (mixed/pure)
' add more methods for each classes (eat, sleep, play, run, swim, fly, etc)
' is vaccinated for pets, is trained for pets

' class: species, breed, toys, pets, pricing
'  


